/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export interface MessageTransmitterV2Interface extends utils.Interface {
  functions: {
    'receiveMessage(bytes,bytes)': FunctionFragment
  }

  getFunction(nameOrSignatureOrTopic: 'receiveMessage'): FunctionFragment

  encodeFunctionData(
    functionFragment: 'receiveMessage',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string

  decodeFunctionResult(
    functionFragment: 'receiveMessage',
    data: BytesLike
  ): Result

  events: {
    'MessageSent(bytes32,bytes)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'MessageSent'): EventFragment
}

export interface MessageSentEventObject {
  messageHash: string
  message: string
}
export type MessageSentEvent = TypedEvent<
  [string, string],
  MessageSentEventObject
>

export type MessageSentEventFilter = TypedEventFilter<MessageSentEvent>

export interface MessageTransmitterV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: MessageTransmitterV2Interface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    receiveMessage(
      message: PromiseOrValue<BytesLike>,
      attestation: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  receiveMessage(
    message: PromiseOrValue<BytesLike>,
    attestation: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    receiveMessage(
      message: PromiseOrValue<BytesLike>,
      attestation: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>
  }

  filters: {
    'MessageSent(bytes32,bytes)'(
      messageHash?: PromiseOrValue<BytesLike> | null,
      message?: null
    ): MessageSentEventFilter
    MessageSent(
      messageHash?: PromiseOrValue<BytesLike> | null,
      message?: null
    ): MessageSentEventFilter
  }

  estimateGas: {
    receiveMessage(
      message: PromiseOrValue<BytesLike>,
      attestation: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    receiveMessage(
      message: PromiseOrValue<BytesLike>,
      attestation: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
