/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export interface TokenMessengerV2Interface extends utils.Interface {
  functions: {
    'depositForBurnWithHook(uint256,uint32,bytes32,address,bytes32,uint32)': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic: 'depositForBurnWithHook'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'depositForBurnWithHook',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string

  decodeFunctionResult(
    functionFragment: 'depositForBurnWithHook',
    data: BytesLike
  ): Result

  events: {}
}

export interface TokenMessengerV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: TokenMessengerV2Interface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    depositForBurnWithHook(
      amount: PromiseOrValue<BigNumberish>,
      destinationDomain: PromiseOrValue<BigNumberish>,
      mintRecipient: PromiseOrValue<BytesLike>,
      burnToken: PromiseOrValue<string>,
      destinationCaller: PromiseOrValue<BytesLike>,
      minFinalityThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  depositForBurnWithHook(
    amount: PromiseOrValue<BigNumberish>,
    destinationDomain: PromiseOrValue<BigNumberish>,
    mintRecipient: PromiseOrValue<BytesLike>,
    burnToken: PromiseOrValue<string>,
    destinationCaller: PromiseOrValue<BytesLike>,
    minFinalityThreshold: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    depositForBurnWithHook(
      amount: PromiseOrValue<BigNumberish>,
      destinationDomain: PromiseOrValue<BigNumberish>,
      mintRecipient: PromiseOrValue<BytesLike>,
      burnToken: PromiseOrValue<string>,
      destinationCaller: PromiseOrValue<BytesLike>,
      minFinalityThreshold: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>
  }

  filters: {}

  estimateGas: {
    depositForBurnWithHook(
      amount: PromiseOrValue<BigNumberish>,
      destinationDomain: PromiseOrValue<BigNumberish>,
      mintRecipient: PromiseOrValue<BytesLike>,
      burnToken: PromiseOrValue<string>,
      destinationCaller: PromiseOrValue<BytesLike>,
      minFinalityThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    depositForBurnWithHook(
      amount: PromiseOrValue<BigNumberish>,
      destinationDomain: PromiseOrValue<BigNumberish>,
      mintRecipient: PromiseOrValue<BytesLike>,
      burnToken: PromiseOrValue<string>,
      destinationCaller: PromiseOrValue<BytesLike>,
      minFinalityThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
