/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type {
  MessageTransmitterV2,
  MessageTransmitterV2Interface,
} from '../MessageTransmitterV2'

const _abi = [
  {
    inputs: [
      {
        internalType: 'bytes',
        name: 'message',
        type: 'bytes',
      },
      {
        internalType: 'bytes',
        name: 'attestation',
        type: 'bytes',
      },
    ],
    name: 'receiveMessage',
    outputs: [
      {
        internalType: 'bool',
        name: 'success',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'messageHash',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'bytes',
        name: 'message',
        type: 'bytes',
      },
    ],
    name: 'MessageSent',
    type: 'event',
  },
] as const

export class MessageTransmitterV2__factory {
  static readonly abi = _abi
  static createInterface(): MessageTransmitterV2Interface {
    return new utils.Interface(_abi) as MessageTransmitterV2Interface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MessageTransmitterV2 {
    return new Contract(address, _abi, signerOrProvider) as MessageTransmitterV2
  }
}
