/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type {
  TokenMessengerV2,
  TokenMessengerV2Interface,
} from '../TokenMessengerV2'

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        internalType: 'uint32',
        name: 'destinationDomain',
        type: 'uint32',
      },
      {
        internalType: 'bytes32',
        name: 'mintRecipient',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: 'burnToken',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'destinationCaller',
        type: 'bytes32',
      },
      {
        internalType: 'uint32',
        name: 'minFinalityThreshold',
        type: 'uint32',
      },
    ],
    name: 'depositForBurnWithHook',
    outputs: [
      {
        internalType: 'bytes32',
        name: '_messageHash',
        type: 'bytes32',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const

export class TokenMessengerV2__factory {
  static readonly abi = _abi
  static createInterface(): TokenMessengerV2Interface {
    return new utils.Interface(_abi) as TokenMessengerV2Interface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenMessengerV2 {
    return new Contract(address, _abi, signerOrProvider) as TokenMessengerV2
  }
}
